# Use this changelog template to create an entry for release notes.

# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: cmd/opampsupervisor

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Add support for total control of configuration merging through magic configuration files

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [39963]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: |
  The magic configuration files can be used through the `agent::config_files` option to control the order
  in which configuration is merged. This allows greater customization of this feature, so that it can adapt
  many use cases without requiring code changes.

  This feature keeps backwards compatibility with previous behavior by injecting the magic config files where
  necessary if none of them are explicitly present in the list of config files. As long as a single magic file
  is present no automagic injection happens.

  It's important to know that omitting one or more of the magic config files can cause the Supervisor and Agent
  to misbehave (i.e. unexpected resource attributes, broken agent telemetry or broken OpAMP connection between
  Agent and Supervisor).

  Configuration is merged from the top of the list to the bottom, in order. This means that the first configuration
  files will get overwritten by the later ones.

  Here's a list of the avaialable magic configuration options and what they represent:

  - "$BUILTIN_CONFIG": configuration that doesn't affect how it works (resource, identifying and non-identifying attributes, etc.).
  - "$OPAMP_EXTENSION_CONFIG": configuration for the agent's OpAMP extension to connect to the Supervisor.
  - "$OWN_METRICS_CONFIG": configuration for the agent's own telemetry.
  - "$REMOTE_CONFIG": remote configuration received by the Supervisor.

  Here's an example that could be used to configure the Agent:

  ```
  agent:
    config_files:
    - $OPAMP_EXTENSION_CONFIG
    - $OWN_METRICS_CONFIG
    - $BUILTIN_CONFIG
    - base_config.yaml
    - $REMOTE_CONFIG
    - compliance_config.yaml
  ```
# If your change doesn't affect end users or the exported elements of any package,
# you should instead start your pull request title with [chore] or use the "Skip Changelog" label.
# Optional: The change log or logs in which this entry should be included.
# e.g. '[user]' or '[user, api]'
# Include 'user' if the change is relevant to end users.
# Include 'api' if there is a change to a library API.
# Default: '[user]'
change_logs: [user]
